from typing import List
from pydantic import BaseModel, Field
from typing import Optional

class TokenUsage(BaseModel):
    """Aggregated token usage across all agents."""

    agent_name: str
    input_tokens: int
    output_tokens: int
    total_tokens: int


class ImageAnalysis(BaseModel):
    """Single image analysis produced by the Curator agent."""
    
    garment_type: str
    color_palette: List[str]
    silhouette: str
    texture_or_fabric: str
    style_era: str
    occasion: str
    standout_detail: str
    image_index: int | None = None
    filename: str | None = None


class MoodCluster(BaseModel):
    """Single images sharing a thematic mood, from the Stylist agent."""

    mood_title: str
    sub_tags: List[str]
    image_indices: List[int]
    styling_rationale: str


class MoodClusters(BaseModel):
    """Group of Mood Clusters"""

    clusters: List[MoodCluster]


class EditorialCard(BaseModel):
    """Single Image Editorial Card generate by the Editor agent"""
    
    card_index: int
    brand_or_designer: str
    product_type: str
    vibe_description: str


class EditorialCards(BaseModel):
    """Group of Editorial Cards"""

    cards: List[EditorialCard]


class FinalLookbookCard(BaseModel):
    """Single Final Lookbook Card generated by the Director agent"""

    card_number: str
    mood_title: str
    sub_tags: List[str]
    brand_or_designer: str
    product_type: str
    vibe_description: str


class WeeklyLookbook(BaseModel):
    """Weekly Lookbook JSON generated by the Director agent"""

    edition_title: str
    total_moods: int
    collection: List[FinalLookbookCard]


class CoverArtwork(BaseModel):
    """Cinematic prompt used to generate the magazine cover."""

    edition_title: str
    positive_prompt: str  
    visual_language: str
    color_palette: List[str]
    camera_style: str  
    negative_prompt: str
    art_direction: str
    image_path: str | None = None
    image_hash: str | None = None


class MoodArtwork(BaseModel):
    """Image generation prompt for one editorial mood card."""

    card_number: str
    mood_title: str
    positive_prompt: str
    negative_prompt: str
    image_path: str | None = None
    image_hash: str | None = None


class VisualLookbook(BaseModel):
    """Output produced by the Visual Director Agent."""

    cover: CoverArtwork
    moods: List[MoodArtwork]

class GeneratedImage(BaseModel):
    """Represents a generated image, including its path, hash, seed, and whether it was cached."""

    image_path: str
    image_hash: str
    seed: int
    cached: bool