from typing import List
from pydantic import BaseModel, Field
from typing import Optional

class TokenUsage(BaseModel):
    """Aggregated token usage across all agents."""

    agent_name: str
    input_tokens: int
    output_tokens: int
    total_tokens: int


class ImageAnalysis(BaseModel):
    """Single image analysis produced by the Curator agent."""
    
    garment_type: str
    color_palette: List[str]
    silhouette: str
    texture_or_fabric: str
    style_era: str
    occasion: str
    standout_detail: str
    image_index: int | None = None
    filename: str | None = None


class MoodCluster(BaseModel):
    """Single images sharing a thematic mood, from the Stylist agent."""

    mood_title: str
    sub_tags: List[str]
    image_indices: List[int]
    styling_rationale: str


class MoodClusters(BaseModel):
    """Group of Mood Clusters"""

    clusters: List[MoodCluster]


class EditorialCard(BaseModel):
    """Single Image Editorial Card generate by the Editor agent"""
    
    card_index: int
    brand_or_designer: str
    product_type: str
    vibe_description: str


class EditorialCards(BaseModel):
    """Group of Editorial Cards"""

    cards: List[EditorialCard]


class FinalLookbookCard(BaseModel):
    """Single Final Lookbook Card generated by the Director agent"""

    card_number: str
    mood_title: str
    sub_tags: List[str]
    brand_or_designer: str
    product_type: str
    vibe_description: str


class WeeklyLookbook(BaseModel):
    """Weekly Lookbook JSON generated by the Director agent"""

    edition_title: str
    total_moods: int
    collection: List[FinalLookbookCard]